### ISSUE TITLE
Django - option to exclude web server name from separating services

### ISSUE THREAD

**Issue by jamesjsanders** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#32]
# Issue
Need the ability to excluded the **"Web server name"** from separating out the Django service and allow grouping the Django service into one identity.

# Example of service in current state being separated out: 
![image](https://user-images.githubusercontent.com/11224488/93520540-7c021f80-f8e3-11ea-97db-c45f250f1464.png)

# Example service properties:
![image](https://user-images.githubusercontent.com/11224488/93521141-748f4600-f8e4-11ea-9eff-2bfb729df665.png)

**Comment by dlopes7** [comment]
This is pretty bad, I need to review the web server name detection logic! Thanks for reporting, will take a look ASAP

**Comment by dlopes7** [comment]
FYI, you can set the environment variable `AUTODYNATRACE_VIRTUAL_HOST` to some value and this will be used as the web server name instead.

**Comment by jamesjsanders** [comment]
The only problem I see with using **_"AUTODYNATRACE_VIRTUAL_HOST"_** as an env. variable is it would overwrite for all request and would loose insight into virtual domain being passed, correct?

**Comment by dlopes7** [comment]
Correct, I am working on a better logic to determine the domain, the solution above is just a workaround to avoid the spam of services

**Comment by avodaqstephan** [comment]
Hej @dlopes7 & @jamesjsanders, 

any news on that topic? How did you end up solving it @jamesjsanders?
