### ISSUE TITLE
support for psycopg2 DB driver

### ISSUE THREAD

**Issue by kasi-january** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#40]
I was hoping DT could (quickly) add support for tracing DB requests made via the psycopg2 driver ([the most popular DB driver for postgreSQL](https://pypi.org/project/psycopg2/))

**Comment by dlopes7** [comment]
PRs are welcome

**Comment by kasi-january** [comment]
@dlopes7 My company is a customer of DT and we were told there would be some correspondence about whether this would be possible or not.

**Comment by dlopes7** [comment]
@kasi-january definitely possible!

**Comment by kasi-january** [comment]
@dlopes7 and the engineer said they would work on it if it was possible :) I can DM you more details if you would like

**Comment by kasi-january** [comment]
@avodaqstephan what postgres driver are you using? we are using psycopg2 with flask.

**Comment by avodaqstephan** [comment]
Same here. Copy paste from our requirements.txt 'psycopg2-binary==2.8.5'

**Comment by amarlot** [comment]
Hello,

We are using this nice package autodynatrace to monitor our python code. It works fine except for database call done with psycopg2 (without any framework).

I hope it will be implemented soon.

We definitivelly not have the knowledge to do that on our own.

**Comment by dlopes7** [comment]
@amarlot and @kasi-january psycopg2 support has been added to 1.0.72, could you please test it?

**Comment by kasi-january** [comment]
@dlopes7  thank you so much! its working for me within flask and docker container
