### ISSUE TITLE
Dynatrace create new service after each deployment/code change

### ISSUE THREAD

**Issue by amarlot** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#41]
Hello,

First things : I would like to thank you for this amazing "pluggin". It helps us a lot to instrument our python application. I hope one day it will be out of the box inside dynatrace.

We are using docker/kubernetes to deploy our python flask app with uwsgi. Each time we deploy a new version, the old service disapear and a new service is create with the same name. I don't understand why.
For other services like nginx/phpfpm, the service stays the same between each code change and each deployment.

Exemple : 
![image](https://user-images.githubusercontent.com/10206313/103870646-4bc9d100-50cc-11eb-9c18-506853cd21a7.png)

We set up those variables for this app for instance : (Everything seems ok)
![image](https://user-images.githubusercontent.com/10206313/103870842-8af82200-50cc-11eb-8020-2c802f4836f4.png)

Any idea why we have new services created after each deployment ? (It is not our goal as we can't follow response time trend after each deploy).

Thanks a lot,
Alexandre

**Comment by dlopes7** [comment]
@amarlot when you go to the service screen, what property is different between these services?

**Comment by amarlot** [comment]
Hello @dlopes7,

THanks for your quick feedback. This is the issue i don't see any except the webserver. Very strange :/ 

First time i see that and i have the case for all my container python with autodynatrace (we use it everywhere ! so helpfull).

Alex

![image](https://user-images.githubusercontent.com/10206313/104040691-435ebc80-51d8-11eb-82b1-551430d2b82d.png)

![image](https://user-images.githubusercontent.com/10206313/104040760-583b5000-51d8-11eb-9837-18831b29a4f1.png)

**Comment by dlopes7** [comment]
@amarlot  I believe you can fix this by setting the environment variable `AUTODYNATRACE_VIRTUAL_HOST`. In your case the virtual host/web server name is dynamic.
