### ISSUE TITLE
FastAPI Support

### ISSUE THREAD

**Issue by jgriepentrog** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#42]
Hello,

Would it be possible to have [FastAPI](https://fastapi.tiangolo.com/) support added for auto instrumentation?

**Comment by dlopes7** [comment]
@jgriepentrog FastAPI support has been added to 1.0.77, feedback is welcomed!

**Comment by jgriepentrog** [comment]
Thank you! Will hopefully be able to test in the upcoming couple of weeks.
