### ISSUE TITLE
Http request reported as http (port 80) but it should be https (443)

### ISSUE THREAD

**Issue by amarlot** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#44]
Hello,

We are using heavily your pluggin to instrument our python fask web app. Thanks again !

We noticed a small bugs when we call externals apis. Indeed the url is displayed with http and port 80 even if we call an https apis on port 443.

For instance, autodynatrace detect an http call (port 80) but in really we called an https endpoint (for sure) :
![image](https://user-images.githubusercontent.com/10206313/105366572-cbdd5400-5bff-11eb-8195-660183265892.png)

We use Requests library to call external api (https://pypi.org/project/requests/)
![image](https://user-images.githubusercontent.com/10206313/105368052-69855300-5c01-11eb-9d00-cb52808b0a85.png)

Exemple of our code (quite basic) :
![image](https://user-images.githubusercontent.com/10206313/105368029-60948180-5c01-11eb-98f5-e732b9e5c6fb.png)

I saw you don't suport Requests library but it is intrumented anyway ! I guess it used being the scene httplib)

Thanks a lot,
Alexandre

**Comment by dlopes7** [comment]
This is fixed in 1.075
