### ISSUE TITLE
Service level metrics missing in Dynatrace - Probably related to "AUTODYNATRACE_FORKABLE"

### ISSUE THREAD

**Issue by avodaqstephan** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#47]
Hi @dlopes7 

it has been quite a while we used version 1.0.57 and now went up to latest version. 
Because we use Django, we have a little snippet in our settings.py which will include autodynatrace if "AUTOWRAPT_BOOTSTRAP" is set.

```
if env("AUTOWRAPT_BOOTSTRAP", str, ""):
    INSTALLED_APPS += ["autodynatrace.wrappers.django"]
```

So what is the problem?

- The OneAgents do not report any problems and they deliver information about host, processes etc.
- Autodynatrace is not reporting a problem. Here are some lines from the debug log. The only thing which is fishy is the missing "app_name" but it should work without it and is not raising an exception.

> [2021-02-12 13:59:52 +0100] [62] [DEBUG] GET /admin/
2021-02-12 13:59:52,943: 62 DEBUG autodynatrace - process_request: Tracing request http://10.0.1.100:8000/admin/
2021-02-12 13:59:52,943 - DEBUG - middlewares - Tracing request http://10.0.1.100:8000/admin/
2021-02-12 13:59:52,943: 62 DEBUG autodynatrace - get_app_name: Resolved app_name as 'None' from resolving the path
2021-02-12 13:59:52,943 - DEBUG - utils - Resolved app_name as 'None' from resolving the path
2021-02-12 13:59:52,944: 62 DEBUG autodynatrace - process_view: Starting view tracer django.contrib.admin.sites.index
2021-02-12 13:59:52,944 - DEBUG - middlewares - Starting view tracer django.contrib.admin.sites.index

But when I look at Dynatrace UI, I've no insights of the services. Just on the process level.

![image](https://user-images.githubusercontent.com/58725083/107772047-f5d7f100-6d3b-11eb-98cf-c53adc56302f.png)

From the logs I can see, that the instrumentation should've worked:

> 021-02-12 13:43:14,587: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument celery  
2021-02-12 13:43:14,589: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument django  
2021-02-12 13:43:14,751: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument concurrent  
2021-02-12 13:43:14,751: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument urllib  
2021-02-12 13:43:14,752: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument subprocess  
2021-02-12 13:43:14,753: 9 INFO autodynatrace - instrument: Instrumented 5/19 libraries (celery, concurrent, django, subprocess, urllib). Will instrument when imported: (confluent_kafka, cx_Oracle, flask, grpc, paramiko, pika, psycopg2, pymongo, pysnmp, redis, ruxit, sqlalchemy, suds, tornado)  
2021-02-12 14:43:15,774 - DEBUG - environ - get 'PROD' casted as '<class 'bool'>' with default 'False'  

Any ideas?

Infrastructure by the way is Kubernetes (EKS). Dynatrace is installed via the operator. Nothing special here.

Kind regards,
Stephan

**Comment by avodaqstephan** [comment]
I played around with different versions and different ENV variables and it turned out, that other projects are not correctly monitored anymore as well.

I'm able to successfully run `autodynatrace` with version `1.0.75` and the environment variable `AUTOWRAPT_BOOTSTRAP=autodynatrace` without any code changes. Thats awesome @dlopes7 !

But the root cause seems to be the environment variable `AUTODYNATRACE_FORKABLE=True`.
We've set that in the past because ... good question ... I think we needed that to support sub processes of gunicorn and celery.  As soon as I set this guy to False, everything started working again.

I sadly can't tell at which version of autodynatrace this actually broke but right now it is not working for `1.0.40`, `1.0.57` and `1.0.75`.
We also updated `gunicorn` to `20.0.4` from `19.9.0`. I'm not sure how to pinpoint the problem from here on, if you need more information from my side, please let me know. 

Kind regards and have a great weekend!

**Comment by dlopes7** [comment]
Thanks for the report.

In theory every time a parent process spawns child processes, we need to set `AUTODYNATRACE_FORKABLE` on the Parent process, in order to monitor the children that were spawned, it is strange that you needed to set it to False for things to work again

What is the first line in the logs when you get no services? The line that reports the AgentState

`DEBUG autodynatrace - init: Initialized autodynatrace with AgentState: 0`

**Comment by avodaqstephan** [comment]
Here you go.

**AUTODYNATRACE_FORKABLE=False**

> 2021-02-12 16:31:09,731: 9 DEBUG autodynatrace - init: Initialized autodynatrace with AgentState: 0  
> 2021-02-12 16:31:09,731 - DEBUG - sdk - Initialized autodynatrace with AgentState: 0  
> 2021-02-12 16:31:09,733: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument celery  
> 2021-02-12 16:31:09,733 - DEBUG - __init__ - Attempting to instrument celery  
> 2021-02-12 16:31:09,734: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument django  
> 2021-02-12 16:31:09,734 - DEBUG - __init__ - Attempting to instrument django  
> 2021-02-12 16:31:09,736: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument concurrent  
> 2021-02-12 16:31:09,736 - DEBUG - __init__ - Attempting to instrument concurrent  
> 2021-02-12 16:31:09,737: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument urllib  
> 2021-02-12 16:31:09,737 - DEBUG - __init__ - Attempting to instrument urllib  
> 2021-02-12 16:31:09,738: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument subprocess  
> 2021-02-12 16:31:09,738 - DEBUG - __init__ - Attempting to instrument subprocess  
> 2021-02-12 16:31:09,738: 9 INFO autodynatrace - instrument: Instrumented 5/19 libraries (celery, concurrent, django, subprocess, urllib). Will instrument when imported: (confluent_kafka, cx_Oracle, flask, grpc, paramiko, pika, psycopg2, pymongo, pysnmp, redis, ruxit, sqlalchemy, suds, tornado)  
> 2021-02-12 16:31:09,738 - INFO - __init__ - Instrumented 5/19 libraries (celery, concurrent, django, subprocess, urllib). Will instrument when imported: (confluent_kafka, cx_Oracle, flask, grpc, paramiko, pika, psycopg2, pymongo, pysnmp, redis, ruxit, sqlalchemy, suds, tornado)  
> 2021-02-12 16:31:10,509 - DEBUG - environ - get 'PROD' casted as '<class 'bool'>' with default 'False'  


**AUTODYNATRACE_FORKABLE=True**

> 2021-02-12 20:24:20,235: 9 DEBUG autodynatrace - init: Initialized autodynatrace with AgentState: 1
> 2021-02-12 20:24:20,235 - DEBUG - sdk - Initialized autodynatrace with AgentState: 1
> 2021-02-12 20:24:20,236: 9 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 1
> 2021-02-12 20:24:20,236 - WARNING - sdk - Could not initialize the OneAgent SDK, AgentState: 1
> 2021-02-12 20:24:20,237: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument celery
> 2021-02-12 20:24:20,237 - DEBUG - __init__ - Attempting to instrument celery
> 2021-02-12 20:24:20,238: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument django
> 2021-02-12 20:24:20,238 - DEBUG - __init__ - Attempting to instrument django
> 2021-02-12 20:24:20,242: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument concurrent
> 2021-02-12 20:24:20,242 - DEBUG - __init__ - Attempting to instrument concurrent
> 2021-02-12 20:24:20,243: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument urllib
> 2021-02-12 20:24:20,243 - DEBUG - __init__ - Attempting to instrument urllib
> 2021-02-12 20:24:20,243: 9 DEBUG autodynatrace - instrument_lib: Attempting to instrument subprocess
> 2021-02-12 20:24:20,243 - DEBUG - __init__ - Attempting to instrument subprocess
> 2021-02-12 20:24:20,245: 9 INFO autodynatrace - instrument: Instrumented 5/19 libraries (celery, concurrent, django, subprocess, urllib). Will instrument when imported: (confluent_kafka, cx_Oracle, flask, grpc, paramiko, pika, psycopg2, pymongo, pysnmp, redis, ruxit, sqlalchemy, suds, tornado)
> 2021-02-12 20:24:20,245 - INFO - __init__ - Instrumented 5/19 libraries (celery, concurrent, django, subprocess, urllib). Will instrument when imported: (confluent_kafka, cx_Oracle, flask, grpc, paramiko, pika, psycopg2, pymongo, pysnmp, redis, ruxit, sqlalchemy, suds, tornado)
> 2021-02-12 20:24:20,999 - DEBUG - environ - get 'PROD' casted as '<class 'bool'>' with default 'False'

**Comment by dlopes7** [comment]
Ok, Agent State 1 is expected when using the variable.

One last question, how do you start django and celery? Could you share the gunicorn command?

**Comment by avodaqstephan** [comment]
Django: `gunicorn -w 4 -b 0.0.0.0:8000 --reload website.wsgi`
Celery: `celery -A website worker -E --beat --scheduler django --loglevel=info`

**Comment by avodaqstephan** [comment]
Let me know if you need more information from my side. We can also schedule a call if you like.

**Comment by dlopes7** [comment]
Hi,

I just ran some tests with autodynatrace 1.0.75

**Django with gunicorn**


Always add "autodynatrace.wrappers.django" to INSTALLED APPS (I am looking into ways of doing that automatically)

Option 1 

- **Don't set** `AUTODYNATRACE_FORKABLE`, autodynatrace is already imported at childen
- **Don't set** `AUTOWRAPT_BOOTSTRAP`, this will instrument gunicorn itself (the parent) instead

Option 2

- Set `AUTOWRAPT_BOOTSTRAP` and `AUTODYNATRACE_FORKABLE`.
- This is because we are now instrumenting the gunicorn process, but we need the OneAgent SDK active on the django processes instead (children)

In summary, you either set no variables, or set both to get Django to work with gunicorn.
In both cases, `autodynatrace.wrappers.django `will need to be added to INSTALLED_APPS.

Example: 
`AUTOWRAPT_BOOTSTRAP=autodynatrace AUTODYNATRACE_FORKABLE=True gunicorn -w 4 -b 0.0.0.0:8000 --reload website.wsgi`

Or simply: `gunicorn -w 4 -b 0.0.0.0:8000 --reload website.wsg` (without setting any of those two variables)

**Celery**

Celery has nothing special, for the tasks you can either set the `AUTOWRAPT_BOOTSTRAP` variable or `import autodynatrace` directly on the tasks files, both should generate purepaths, there is logic to check if we are attempting to instrument celery and use the correct flag.

Example: `AUTOWRAPT_BOOTSTRAP=autodynatrace celery -A tasks worker -E --beat --loglevel=info`

**Comment by avodaqstephan** [comment]
Hi, 

so I tried every option but it is not working for Django. Celery works fine. 
Because we use both, I wanted to use `Option 2`.

So I set: 

**ENV**

- `AUTODYNATRACE_FORKABLE: true`
- `AUTOWRAPT_BOOTSTRAP: "autodynatrace"`

**settings.py**

- `import autodynatrace`
```
INSTALLED_APPS = [
    'autodynatrace.wrappers.django',
    ...
```

Agent reports `init: Initialized autodynatrace with AgentState: 1` at the beginning. I can't go deeper than the process level. Celery works fine.

Setting `AUTODYNATRACE_FORKABLE: false` will give me service level insights in Django but Celery stops working.

So I need to set 2 different environment variables now. Django without `forkable` and Celery with it. Which is a step back compared to the solution we had in place before. I'm confused because you said, you tested it, and it worked for you with Option2 for both. I'm out of ideas right now.

**Comment by avodaqstephan** [comment]
Hi David, 

I found something but can't really explain it atm. 

So a real basic projects has a `run_django.sh` which has uses this to startup gunicorn:

`gunicorn -w 4 -b 0.0.0.0:8000 --reload website.wsgi` In combination with AUTOWRAPT_BOOTSTRAP=autodynatrace AUTODYNATRACE_FORKABLE=True this doesn't work.

Now I tried 
`gunicorn -w 4 -b 0.0.0.0:8000 website.wsgi --preload`. In combination with AUTOWRAPT_BOOTSTRAP=autodynatrace AUTODYNATRACE_FORKABLE=True this **does** work.

Here is the documentation part from [Gunicorns preload feature
](https://docs.gunicorn.org/en/stable/settings.html#preload-app).

The thing is, we never had this `--preload` in one of our apps before but autodynatrace worked in the past. It seems like --preload is a great addition for us so we'll keep it, still there is an open question why we need to this to enable the full potential of autodynatrace.

**Comment by dlopes7** [comment]
Thanks for the update.

The behavior of initializing the OneAgent SDK on a parent vs a forked process is out of my control in this wrapper.
I believe this issue (why preload is required with gunicorn) makes more sense at https://github.com/Dynatrace/OneAgent-SDK-for-Python
