### ISSUE TITLE
Confluent wrapper waits kafka-topic as args

### ISSUE THREAD

**Issue by CrazyLionHeart** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#53]
If I pass kafka-topic in kwargs, I got error: `Index error: tuple index out of of range` in line [45](https://github.com/dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation/blob/master/autodynatrace/wrappers/confluent_kafka/wrapper.py#L45)

I think, we need add check before using `args` at code:

```
msi_handle = sdk.create_messaging_system_info(
  "Kafka", args[0], MessagingDestinationType.TOPIC, Channel(ChannelType.TCP_IP, servers),
 )
``` 
Or use `kwags['topic']` value implicity

**Comment by haiderstats** [comment]
Also seeing this issue. We don't want to use args here so we currently would have to monkey patch to get around this.
