### ISSUE TITLE
Fail to display end to end service flow of   python apps 

### ISSUE THREAD

**Issue by holylai830830** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#65]
I've have try to using and sucessfully instrument a pythin app with oneagent SDK , but we found we can not display a END to END service flow
suppose , the ngnix front end service (haproxy)  will call a python backend service
but the page show a unmonitored service call a python service rather than frontend to backup end
do i need to additional configure for custom services to display END to END service flow?

![image](https://user-images.githubusercontent.com/34336275/191263693-420df4e3-5395-4e81-b1e3-b5e3bfbc3716.png)

 https://www.dynatrace.com/news/blog/end-to-end-request-monitoring-for-popular-python-frameworks-with-oneagent-sdk/
we are using the above autodynatrace packages to instrument our apps

**Comment by dlopes7** [comment]
This is done via a header called `x-dynatrace`, which should be injected into `nginx` when you installed the OneAgent.

Is the `x-dynatrace` header present when the request arrives in your Flask application? You can log the headers to check.

If it is not present, you need to open a support case with Dynatrace to investigate nginx injection, or check if you have something removing headers.
