### ISSUE TITLE
oraclelinux:7.9 - ERROR: ld.so: object liboneagentproc.so from /etc/ld.so.preload cannot be preloaded: ignored.

### ISSUE THREAD

**Issue by pharbuz-spica** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#67]
Hi,

We have a problem with the autodynatrace library running on OpenShift pod using image oraclelinux:7.9. The problem depends on that after installation we get the following error:
`sh-4.2$ python3 pip list`
`ERROR: [ld.so](http://ld.so/): object '/opt/dynatrace/oneagent/agent/lib64/[liboneagentproc.so](http://liboneagentproc.so/)' from LD_PRELOAD cannot be preloaded: ignored.`
`ERROR: [ld.so](http://ld.so/): object '/opt/dynatrace/oneagent/agent/bin/current/linux-x86-64/[liboneagentproc.so](http://liboneagentproc.so/)' from /etc/[ld.so](http://ld.so/).preload cannot be preloaded: ignored.`
`2022-10-10 17:54:43,430: 17 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 3
python3: can't open file 'pip': [Errno 2] No such file or directory`
`sh-4.2$ python3 -m pip list`
`ERROR: [ld.so](http://ld.so/): object '/opt/dynatrace/oneagent/agent/lib64/[liboneagentproc.so](http://liboneagentproc.so/)' from LD_PRELOAD cannot be preloaded: ignored.`
`ERROR: [ld.so](http://ld.so/): object '/opt/dynatrace/oneagent/agent/bin/current/linux-x86-64/[liboneagentproc.so](http://liboneagentproc.so/)' from /etc/[ld.so](http://ld.so/).preload cannot be preloaded: ignored.`
`2022-10-10 17:54:56,304: 18 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 3`
`ERROR: [ld.so](http://ld.so/): object '/opt/dynatrace/oneagent/agent/lib64/[liboneagentproc.so](http://liboneagentproc.so/)' from LD_PRELOAD cannot be preloaded: ignored.`
`ERROR: [ld.so](http://ld.so/): object '/opt/dynatrace/oneagent/agent/bin/current/linux-x86-64/[liboneagentproc.so](http://liboneagentproc.so/)' from /etc/[ld.so](http://ld.so/).preload cannot be preloaded: igno`

The OpenShift cluster is instrumented using Dynatrace Operator 0.9.0.

**Comment by dlopes7** [comment]
This is not an issue we can help with, please open a support ticket with Dynatrace.
