### ISSUE TITLE
Encountering "Could not initialize the OneAgent SDK, AgentState: 3" warning when running the server

### ISSUE THREAD

**Issue by oruchkin** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#85]
**Issue:**
After executing the command `python manage.py runserver` I encountered the following `warning` messages in my console:

```
2023-07-20 13:10:59,726: 29813 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 3
WARNING:autodynatrace:Could not initialize the OneAgent SDK, AgentState: 3
2023-07-20 13:11:00,290: 29818 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 3
WARNING:autodynatrace:Could not initialize the OneAgent SDK, AgentState: 3
``` 
<img width="846" alt="Screenshot 2023-07-20 at 16 19 28" src="https://github.com/dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation/assets/72818824/a5731847-8ba3-4b31-b3ed-29e30665abf7">

I'm doing it with `django`
i've added  `autodynatrace.wrappers.django`, in installed apps in settings.py. 
Is it bad, can i ignore it? 
How can i fix this warning message?

**Comment by kashirin-dm** [comment]
The same

**Comment by dlopes7** [comment]
You need to have the Dynatrace OneAgent installed on the host where python is running

**Comment by kashirin-dm** [comment]
I used an Alpine image, and when I changed to a regular Python image, the error disappeared.
