### ISSUE TITLE
Agent not found for Django application

### ISSUE THREAD

**Issue by l3risch** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#88]
We use autodynatrace to instrument our Django application. We followed the readme and tried the semi-auto instrumentation (option 2) as well as the instrumentation without code changes (option 1). These are the logs we are getting:

![Bildschirmfoto 2023-09-05 um 11 40 29](https://github.com/dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation/assets/40214757/655ad6ca-433a-4377-bf45-a82e577d8c6e)

![Bildschirmfoto 2023-09-04 um 14 03 11](https://github.com/dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation/assets/40214757/21ca5ec6-23d4-4a7d-8ffc-48516fcd9b8b)

We are using autodynatrace 1.1.1 and agent version 1.7.1 on a Django app which is running in a docker container.

Are we missing any step?

Best regards,

Christian

**Comment by dlopes7** [comment]
Do you have the OneAgent instrumenting that Docker container?

AgentState: 3 means the OneAgent was not found anywhere.

**Comment by l3risch** [comment]
Thank you so much for your input. I misse the step where I set up OneAgent as a Docker Container following this link: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/docker/set-up-dynatrace-oneagent-as-docker-container. Now I am also able to see the 'Service' view of my Django project.
