### ISSUE TITLE
Monitoring AWS Fargate

### ISSUE THREAD

**Issue by U002686** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#90]
**Describe the bug**
Problem performing fargate monitoring.
The method chosen was build-time injection, in classic integration.
After inserting the settings in the docker file when uploading the container, it shows a warning error in the logs. Consequently, we cannot see the containers in dynatrace.

**To Reproduce**
1. Go to documentation https://www.dynatrace.com/support/help/shortlink/aws-fargate#buildtime. 
2. Click on classic integration.
3. Scroll down to step 1.
4. After the configuration, when the container goes up it starts to burst in the log the error:
WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 1"

**Expected behavior**

**Screenshots**
<img width="1213" alt="Screenshot_80" src="https://github.com/dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation/assets/117773539/c1fb1a81-13b4-42c0-a47d-af6135eeb16f">

**Desktop (please complete the following information):**
 - OS: Debian based image

**Comment by dlopes7** [comment]
Please follow the troubleshooting and requirements here: https://github.com/Dynatrace/OneAgent-SDK-for-Python#requirements

Specially around the supported containers (example: can't be alpine)

And please open a ticket with Dynatrace if you still have Agent State 1, after following the requirements and troubleshooting on that page.

This is not an issue with this library, but with the underlying OneAgent not instrumenting the process.
